default:
  plugins:
    - image
    - link
    - media
    - uploadimage

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table | 
  plugins:
    - table