default:
  plugins:
    - image
    - link
    - media

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table | image media
  plugins:
    - table
    - image
    - media
  media_live_embeds: true
